spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
